### PR TITLE
Features in the Index page

### PR DESCRIPTION
**Pull request by MrGKanev**
## Description

Showing our features on the index page with images. I have left the full-size images in the folder on purpose. I'm not sure how much I like the optimized ones. There is a possibility of optimizing/minifying them again but using other tools.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [X] Locally

### CODE REVIEW

**Comment by l-alexandrov** [comment]
What are the `*.png` image versions for? Probably some kind of fallback mechanism?

**Review by l-alexandrov — COMMENTED** [review]
What are the *.png image versions for? Probably some kind of fallback mechanism?

**Comment by MrGKanev** [comment]
> What are the *.png image versions for? Probably some kind of fallback mechanism?

Those are the full-sized images unedited as mentioned in the PR.

**Comment by l-alexandrov** [comment]
I see. My bad then.

**Review by l-alexandrov — APPROVED** [review]

**Pull request merged**
