### PR TITLE
Latest Composer

### PR DESCRIPTION
**Pull request by MrGKanev**
## Description

We don't have any custom logic regarding our need for the composer. This way we will use the newest version and we don't need to manage it anymore. The process is simplified and the build is easier.

## Type of change

Please delete options that are not relevant.

- [X] Enhancement (non-breaking change which improves an existing functionality)

## How Has This Been Tested?

- [X] Locally

### CODE REVIEW

**Comment by l-alexandrov** [comment]
@MrGKanev Would it cause problems when the latest PHP version is changed and we haven't caught up yet?

**Comment by MrGKanev** [comment]
@l-alexandrov only if we are really behind. (which will be bad for other reasons) Even the newest version now only requires PHP 7.2.5 - which is EOL.

**Comment by l-alexandrov** [comment]
So, to sum up, there is a risk, but it's measured and low?

**Comment by MrGKanev** [comment]
@l-alexandrov really low. If we have it, we have bigger problems on our hands.

**Comment by l-alexandrov** [comment]
Got it.

**Review by l-alexandrov — APPROVED** [review]

**Pull request merged**
