### PR TITLE
Use Cases v2

### PR DESCRIPTION
**Pull request by MrGKanev**
## Description

Updating the information regarding how our users use us.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Enhancement (non-breaking change which improves an existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Summary by CodeRabbit

- **Refactor**
  - Revamped the layout and content structure for the use case descriptions page.

### CODE REVIEW

**Review by l-alexandrov — CHANGES_REQUESTED** [review]
Congratulations for improving it. It's now even more comprehensive. Let's add some visuals though, probably some undraw.co images or badges as in the previous version. Too much text condensed is not a good idea.

**Comment by MrGKanev** [comment]
> Congratulations for improving it. It's now even more comprehensive. Let's add some visuals though, probably some undraw.co images or badges as in the previous version. Too much text condensed is not a good idea.

You are correct on that one, but too many people use "already done" images and it looks unprofessional. That is why I haven't added anything as images. - it takes too much time for me to draw anything. We can merge this now and add a to-do for the future.

**Comment by l-alexandrov** [comment]
You are right for the generated and sample images. We can still enrich it visually though. Adding more space and probably adding darker background on chess principle or adding snake-like line between them.

**Comment by MrGKanev** [comment]
Can we merge this one, and do another PR to try to make it look better?

**Comment by l-alexandrov** [comment]
I'm afraid if we leave the improvement for a later stage, we'll bury it in the backlog with lowest priority.

**Pull request merged**
